spring:
  application:
    name: opcua-proto
  data:
    mongodb:
      host: localhost
      port: 27017
      database: meter_data
      collection: meter_readings
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/timeseries_db
    username: postgres
    password: password
    pool:
      initial-size: 10
      max-size: 20

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

opcua:
  endpoint-url: "opc.tcp://172.16.10.237:4841"
  username:
  password:
  application-name: "Spring Boot OPC UA Meter Client"
  subscription-interval: 5000
  node-ids:
    - "ns=2;s=GIUSController.Address"
    - "ns=2;s=GIUSController.DateTime"
    - "ns=2;s=GIUSController.GUID"
    - "ns=2;s=GIUSController.Model"
    - "ns=2;s=GIUSController.Product"

logging:
  level:
    ru.iteco.opcua: DEBUG
    org.eclipse.milo: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics