spring:
  application:
    name: opcua-proto
  data:
    mongodb:
      host: localhost
      port: 27017
      database: meter_data
      collection: meter_readings
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/timeseries_db
    username: postgres
    password: password
    pool:
      initial-size: 10
      max-size: 20

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

opcua:
  endpoints:
    - url: "opc.tcp://172.16.10.237:4841"
      type: heat
      meters:
        - guid: 3e97ec0a-3ad8-4ce8-be06-056e3f19861b
          subs: [1]
        - guid: 59e39388-c93b-4ab6-87d8-eaf608624fa4
          subs: [1]
  application-name: "Spring Boot OPC UA Meter Client"
  subscription-interval: 5000


logging:
  level:
    ru.iteco.opcua: DEBUG
    org.eclipse.milo: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics